modLoader="javafml"
loaderVersion="[45,)"
license="MIT License"

[[mods]]
modId="in_your_world"
version="1.0"
displayName="In Your World"
displayURL="https://www.patreon.com/EBALIA"
logoFile="logo.png"
credits="By EBALIA"
authors="EBALIA"
description="no information"

[[dependencies.in_your_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"



[[dependencies.in_your_world]]
    modId="use_compiled_mods"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.in_your_world]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

